version: "3.7"
services:

  iv3:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_URL: "http://influxdb:8086"
      IV3_ENV: ${IV3_ENV}
    container_name: iv3
    # restart: always
    volumes:
      - type: bind
        source: config.yaml
        target: /go/iv3/config.yaml
    depends_on:
      - influxdb
    ports:
      - "8080:8443"

  influxdb:
    image: "influxdb:2.7.0"
    container_name: influxdb
    volumes:
      - type: bind
        source: _iv3_data/influxdb2
        target: /var/lib/influxdb2
      - type: bind
        source: _iv3_config/influxdb2
        target: /etc/influxdb2
    ports:
      - "8086:8086"