version: "3.7"
services:
  iv3:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_URL: "http://influxdb:8086"
      IV3_ENV: ${IV3_ENV}
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE}
    container_name: iv3
    volumes:
      - type: bind
        source: config.yaml
        target: /go/iv3/config.yaml
      - type: bind
        source: _iv3_ssl/
        target: /go/iv3/_iv3_ssl
    depends_on:
      - influxdb
    ports:
      - "8080:8443"
  influxdb:
    image: influxdb:2.7.0
    container_name: influxdb
    volumes:
      - type: bind
        source: _iv3_data/influxdb2
        target: /var/lib/influxdb2
      - type: bind
        source: _iv3_config/influxdb2
        target: /etc/influxdb2
    ports:
      - "8086:8086"
  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    container_name: datadog-agent
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: true
      DD_DOGSTATSD_PORT: 8125
    ports:
      - "8125:8125/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
